language: ruby
before_install: gem install bundler -v '~> 1.2.0'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
gemfile:
  - Gemfile
  - gemfiles/no-mongo.gemfile
  - gemfiles/rails31.gemfile
services:
  - mongodb
